### ISSUE TITLE
I have no idea how to download this.

### ISSUE THREAD

**Issue by AngelOfCreation** [Worker20/CreateRobotics-1.18#43]
Why is there not a download button available? Is it on the discord? Because every link to the discord is broken.

**Comment by OutCraft-Mods** [comment]
Hi @X66Herobrine66X!
The Mod is currently a WIP *(Work In Progress)* and not publicly downloadable right now.
Would you mind joining the Discord and telling me which links to it are broken? Here's our [official invite](https://discord.gg/jvVbwBYMU9).
